const defaultProxyResources = {
  http: [
    "http://proxysearcher.sourceforge.net/Proxy%20List.php?type=http",
    "https://openproxy.space/list/http",
    "https://proxyspace.pro/http.txt",
    "https://rootjazz.com/proxies/proxies.txt",
    "https://spys.me/proxy.txt",
    "https://proxyhub.me/en/all-http-proxy-list.html",
    "https://proxy-tools.com/proxy/http",
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxyscan.io/download?type=http",
    "https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc&protocols=https",
    "https://cdn.jsdelivr.net/gh/aslisk/proxyhttps/https.txt",
    "https://cdn.jsdelivr.net/gh/clarketm/proxy-list/proxy-list-raw.txt",
    // "https://cdn.jsdelivr.net/gh/hanwayTech/free-proxy-list/https.txt",
    "https://cdn.jsdelivr.net/gh/hendrikbgr/Free-Proxy-Repo/proxy_list.txt",
    "https://cdn.jsdelivr.net/gh/jetkai/proxy-list/online-proxies/txt/proxies-http.txt",
    "https://cdn.jsdelivr.net/gh/mertguvencli/http-proxy-list/proxy-list/data.txt",
    "https://cdn.jsdelivr.net/gh/mmpx12/proxy-list/https.txt",
    "https://cdn.jsdelivr.net/gh/roosterkid/openproxylist/HTTPS_RAW.txt",
    "https://cdn.jsdelivr.net/gh/saschazesiger/Free-Proxies/proxies/http.txt",
    "https://cdn.jsdelivr.net/gh/ShiftyTR/Proxy-List/https.txt",
    "https://cdn.jsdelivr.net/gh/sunny9577/proxy-scraper/proxies.txt",
  ],
  socks4: [
    "http://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks",
    "https://openproxy.space/list/socks4",
    "https://proxyspace.pro/socks4.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://proxyhub.me/en/all-socks4-proxy-list.html",
    "https://proxylist.geonode.com/api/proxy-list?limit…rt_by=lastChecked&sort_type=desc&protocols=socks4",
    "https://www.my-proxy.com/free-socks-4-proxy.html",
    "https://cdn.jsdelivr.net/gh/B4RC0DE-TM/proxy-list/SOCKS4.txt",
    // 'https://cdn.jsdelivr.net/gh/hanwayTech/free-proxy-list/socks4.txt',
    "https://cdn.jsdelivr.net/gh/jetkai/proxy-list/online-proxies/txt/proxies-socks4.txt",
    "https://cdn.jsdelivr.net/gh/roosterkid/openproxylist/SOCKS4_RAW.txt",
    "https://cdn.jsdelivr.net/gh/saschazesiger/Free-Proxies/proxies/socks4.txt",
    "https://cdn.jsdelivr.net/gh/TheSpeedX/PROXY-List/socks4.txt",
  ],
  socks5: [
    "http://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks",
    "https://openproxy.space/list/socks5",
    "https://proxyspace.pro/socks5.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://proxy-tools.com/proxy/socks5",
    "https://proxyhub.me/en/all-sock5-proxy-list.html",
    "https://proxylist.geonode.com/api/proxy-list?limit…rt_by=lastChecked&sort_type=desc&protocols=socks5",
    // 'https://cdn.jsdelivr.net/gh/hanwayTech/free-proxy-list/socks5.txt',
    "https://cdn.jsdelivr.net/gh/HyperBeats/proxy-list/socks5.txt",
    "https://cdn.jsdelivr.net/gh/jetkai/proxy-list/online-proxies/txt/proxies-socks5.txt",
    "https://cdn.jsdelivr.net/gh/mmpx12/proxy-list/socks5.txt",
    "https://cdn.jsdelivr.net/gh/roosterkid/openproxylist/SOCKS5_RAW.txt",
    "https://cdn.jsdelivr.net/gh/saschazesiger/Free-Proxies/proxies/socks5.txt",
    "https://cdn.jsdelivr.net/gh/TheSpeedX/PROXY-List/socks5.txt",
  ],
};

export default defaultProxyResources;
